## PythonDaily40

Create a function that transposes a 2D matrix.

Examples<br>
transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) ➞ [ [1, 2, 3], [1, 2, 3], [1, 2, 3] ] <br>
transpose_matrix([ [5, 5], [6, 7], [9, 1] ]) ➞ [ [5, 6, 9], [5, 7, 1] ]

In [9]:
# solution 1

# matrix = [ [5, 5]
#            [6, 7]
#            [9, 1] ]

def transposeMatrix(matrix):
    transLst1 = []
    for i in range(len(matrix[0])): # 2 columns-->0,1
        transLst2 = []
        for j in range(len(matrix)): # 3 rows-->0,1,2
            num = matrix[j][i]
            # matrix[0][0] --> 5
            # matrix[1][0] --> 6
            # matrix[2][0] --> 9
            transLst2.append(num)
        transLst1.append(transLst2)
    return transLst1

print( transposeMatrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) )
print( transposeMatrix([ [5, 5], [6, 7], [9, 1] ]) )

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[5, 6, 9], [5, 7, 1]]


In [37]:
# solution 2

def transposeMatrix(matrix):

    transpose = [[matrix[y][x] for y in range(len(matrix))] for x in range(len(matrix[0]))]
    return transpose

print( transposeMatrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) )
print( transposeMatrix([ [5, 5], [6, 7], [9, 1] ]) )


[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[5, 6, 9], [5, 7, 1]]


In [49]:
# solution 3

import numpy as np

transposeMatrix1 = np.array([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ])
print(transposeMatrix1.transpose())

transposeMatrix2 = np.array([ [5, 5], [6, 7], [9, 1] ])
print(transposeMatrix2.transpose())

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 9]
 [5 7 1]]
