## PythonDaily40

Create a function that transposes a 2D matrix.

Examples<br>
transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]) ➞ [ [1, 2, 3], [1, 2, 3], [1, 2, 3] ] <br>
transpose_matrix([ [5, 5], [6, 7], [9, 1] ]) ➞ [ [5, 6, 9], [5, 7, 1] ]

In [77]:
def transpose_matrix(matrix):

    transpose = [[matrix[y][x] for y in range(len(matrix))] for x in range(len(matrix[0]))]
    return transpose

print(transpose_matrix([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]))
print(transpose_matrix([ [5, 5], [6, 7], [9, 1] ]))


[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[5, 6, 9], [5, 7, 1]]


In [46]:
import numpy as np

a = np.array([ [1, 1, 1], [2, 2, 2], [3, 3, 3] ])
print(a.transpose())

b = np.array([ [5, 5], [6, 7], [9, 1] ])
print(b.transpose())

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 9]
 [5 7 1]]
